{% set name = "wagtail-factories" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wagtail/wagtail-factories/archive/{{ version }}.tar.gz
  sha256: 1bd25aa44206b5f291fc845b289d87fa238f298d154eea0680fb2aff5f2cba82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - factory_boy >=3.2
    - wagtail >=4.1

test:
  source_files:
    - tests/
  imports:
    - tests
    - tests.testapp
  commands:
    - pip check
  requires:
    - pip
    - factory_boy >=3.2
    - wagtail >=4.1
    - djangorestframework
    - django-taggit
    - pytest ==6.2.5
    - pytest-django ==4.5.0
    - pytest-cov ==3.0.0
    - pytest-pythonpath ==0.7.3
    - coverage ==6.0
    - ruff ==0.2.1

about:
  home: https://github.com/wagtail/wagtail-factories/
  summary: Factory boy classes for wagtail
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
