{% set name = "wagtail-factories" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wagtail/wagtail-factories/archive/v{{ version }}.tar.gz
  sha256: 24b46ba6994b861cf2f13722ffc5b523a4c64e4027d1e43f98e2a1f1793a52da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - django
    - python >={{ python_min }}
    - factory_boy >=3.2,<4
    - wagtail >=6.3

test:
  source_files:
    - tests/
  imports:
    - tests
    - tests.testapp
  commands:
    - pip check
  requires:
    - pip
    - factory_boy >=3.2
    - wagtail >=4.1
    - djangorestframework
    - django-taggit
    - pytest ==6.2.5
    - pytest-django ==4.5.0
    - pytest-cov ==3.0.0
    - pytest-pythonpath ==0.7.3
    - coverage ==6.0
    - ruff ==0.2.1
    - python {{ python_min }}

about:
  home: https://github.com/wagtail/wagtail-factories/
  summary: Factory boy classes for wagtail
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
